import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}/>
        <h1>Welcome to Pepcoding <img src='https://upload.wikimedia.org/wikipedia/commons/d/d3/PSLV_%28DYK%29.png'></img></h1>

      </main>

    </div>
  )
}
